web:
    build: .
    ports:
        - "5000:5000"
    volumes:
        - .:/code
    links:
        - db

# data:
#   restart: no
#   image: postgres:latest
#   volumes:
#     - /var/lib/postgresql
#   command: true

db:
    restart: always
    image: postgres:latest
    # volumes_from:
    #     - data
  # ports:
  #   - "5432:5432"
